# serverless.yml
service: ocpi-cpo-sim-backend

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1

package:
  include:
    - app/**

functions:
  app:
    handler: app/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'